#!/bin/bash

production_additions_and_deletions() {
  git log --author=plagelao@gmail.com --shortstat -- . ":!spec" ":!features" ":!doc" ":!README.md"| \
  awk '/^ [0-9]/ { f += $1; i += $4; d += $6 } \
  END { printf("%d files changed, %d insertions(+), %d deletions(-)", f, i, d) }'
}

test_additions_and_deletions() {
  git log --author=plagelao@gmail.com --shortstat spec features| \
  awk '/^ [0-9]/ { f += $1; i += $4; d += $6 } \
  END { printf("%d files changed, %d insertions(+), %d deletions(-)", f, i, d) }'
}
